name: Tâche Quotidienne 0h, 8h et 12h sur Develop (Montréal)

# Le workflow ne sera déclenché que par le 'schedule' (cron).
on:
  schedule:
    # 0 4 * * * -> Tous les jours à 4h00 UTC (correspond à 00h00 AM EDT à Montréal)
    - cron: '04 5 * * *' 
    # 0 12 * * * -> Tous les jours à 12h00 UTC (correspond à 8h00 AM EDT à Montréal)
    - cron: '0 12 * * *'
    # 0 16 * * * -> Tous les jours à 16h00 UTC (correspond à 12h00 PM EDT à Montréal)
    - cron: '0 16 * * *'
  
  # Optionnel : permet de déclencher le workflow manuellement
  workflow_dispatch:

jobs:
  run_on_schedule:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout de la branche develop
        uses: actions/checkout@v4
        with:
          # Assurez-vous de récupérer la dernière version de la branche develop
          ref: develop 

      - name: Afficher l'heure locale (Montréal) pour vérification
        run: |
          echo "Le workflow a été déclenché à l'heure planifiée (0h, 8h ou 12h à Montréal)."
          # Affiche l'heure à Montréal pour confirmer
          TZ="America/Montreal" date +"Heure locale d'exécution : %H:%M:%S"
          
      # --- Vos actions (build, test, déploiement, etc.) suivent ici ---

      - name: Exécuter les tâches principales
        run: |
          echo "La tâche sur 'develop' est en cours d'exécution."
          # Placez ici les commandes que vous souhaitez exécuter
